export const IS_LOADING_USER = 'IS_LOADING_USER';
export const IS_LOADING_FRONT_PAGE = 'IS_LOADING_FRONT_PAGE';
export const FRONT_PAGE_SUCCESS = 'FRONT_PAGE_SUCCESS';
export const SUB_SUCCESS = 'SUB_SUCCESS';
export const SUB_URL_SUCCESS = "SUB_URL_SUCCESS";
export const ARTICLE_URL_SUCCESS = "ARTICLE_URL_SUCCESS";
export const TOKEN_SUCCESS = "TOKEN_SUCCESS";

export const SET_LOADING = "SET_LOADING";
export const SET_ARTICLE = "SET_ARTICLE";