export const IS_LOADING_USER = 'IS_LOADING_USER';
export const IS_LOADING_FRONT_PAGE = 'IS_LOADING_FRONT_PAGE';
export const FRONT_PAGE_SUCCESS = 'FRONT_PAGE_SUCCESS';
export const SUB_SUCCESS = 'SUB_SUCCESS';
export const SUB_URL_SUCCESS = "SUB_URL_SUCCESS";
export const ARTICLE_URL_SUCCESS = "ARTICLE_URL_SUCCESS";
export const TOKEN_SUCCESS = "TOKEN_SUCCESS";
export const SET_KARMA = "SET_KARMA";
export const SET_USER_COMMENTS = "SET_USER_COMMENTS";
export const SET_USER_SUBMITTED = "SET_USER_SUBMITTED";
export const SET_USER_UPVOTED = "SET_USER_UPVOTED";
export const SET_USER_DOWNVOTED = "SET_USER_DOWNVOTED";

export const SET_LOADING = "SET_LOADING";
export const SET_ARTICLE = "SET_ARTICLE";